# Site settings
title: Iran University of Science and Technology
course_name: Some Course Title
course_description: "هدف از اين درس يادگيري نظريه بازيها و استفاده از روشهاي معرفي شده در اين درس به منظور حل مسائل
.مهندسي است "
course_semester: "Fall 2019"
description: |
    Instructor: 

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/Game_Design" # the subpath of your site, e.g. /blog/
url: "http://zahramomeni.github.io/Game_Design" # the base hostname & protocol for your site
syllabus: http://zahramomeni.github.io/Game_Design/syllabus/
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: broken_twitter 
github_username:  zahramomeni
authorurl: "http://zahramomeni.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
